config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  devise_for :users, :controllers => { :registrations => :registrations}

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :destroy]
      resources :reviews, only: [:create, :destroy] #this is just to test the reviews controller
      resources :mountains, only: [:create, :index, :show, :destroy] do
        resources :reviews, only: [:create]
      end
      resources :upvotes, only: [:create]
      scope :user do
        get 'is_signed_in', to: 'user#is_signed_in?'
      end
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end

  get '/mountains/:id', to: 'static_pages#index'

  resources :mountains do
    resources :reviews, except: [:index, :show]
  end

  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mountain.rb
class Mountain < ApplicationRecord
  STATES = [
    ["AK", "Alaska"],
    ["AL", "Alabama"],
    ["AR", "Arkansas"],
    ["AS", "American Samoa"],
    ["AZ", "Arizona"],
    ["CA", "California"],
    ["CO", "Colorado"],
    ["CT", "Connecticut"],
    ["DC", "District of Columbia"],
    ["DE", "Delaware"],
    ["FL", "Florida"],
    ["GA", "Georgia"],
    ["GU", "Guam"],
    ["HI", "Hawaii"],
    ["IA", "Iowa"],
    ["ID", "Idaho"],
    ["IL", "Illinois"],
    ["IN", "Indiana"],
    ["KS", "Kansas"],
    ["KY", "Kentucky"],
    ["LA", "Louisiana"],
    ["MA", "Massachusetts"],
    ["MD", "Maryland"],
    ["ME", "Maine"],
    ["MI", "Michigan"],
    ["MN", "Minnesota"],
    ["MO", "Missouri"],
    ["MS", "Mississippi"],
    ["MT", "Montana"],
    ["NC", "North Carolina"],
    ["ND", "North Dakota"],
    ["NE", "Nebraska"],
    ["NH", "New Hampshire"],
    ["NJ", "New Jersey"],
    ["NM", "New Mexico"],
    ["NV", "Nevada"],
    ["NY", "New York"],
    ["OH", "Ohio"],
    ["OK", "Oklahoma"],
    ["OR", "Oregon"],
    ["PA", "Pennsylvania"],
    ["PR", "Puerto Rico"],
    ["RI", "Rhode Island"],
    ["SC", "South Carolina"],
    ["SD", "South Dakota"],
    ["TN", "Tennessee"],
    ["TX", "Texas"],
    ["UT", "Utah"],
    ["VA", "Virginia"],
    ["VI", "Virgin Islands"],
    ["VT", "Vermont"],
    ["WA", "Washington"],
    ["WI", "Wisconsin"],
    ["WV", "West Virginia"],
    ["WY", "Wyoming"]
    ]

  belongs_to :creator,
    class_name: 'User',
    foreign_key: "creator_id"

  has_many :reviews

  validates :name, presence: true, uniqueness: true
  validates :city, presence: true
  validates :address, presence: true
  validates :state,
    presence: true,
    inclusion: { in: STATES.map { |state| state[0] } }
  validates :zip, numericality: true, presence: true, length: { is: 5}

  def self.by_rating
   self.all.sort_by{|mountain| mountain.rating}.reverse
  end

  def self.search(search)
    results = self.where("name ILIKE ?", "%#{search}%")
    if results !=[]
      results
    else
      self.all
    end
  end

  def rating
    if reviews.empty?
      0
    else
      reviews.reduce(0) {|sum, review| sum += review.rating} / reviews.count.to_f
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :mountain
  belongs_to :user

  has_many :upvotes

  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  def vote_total
    upvotes.reduce(0) {|sum, upvote| sum += upvote.vote}
  end
end

app/models/upvote.rb
class Upvote < ApplicationRecord
 belongs_to :user
 belongs_to :review
 validates :vote, numericality: { greater_than_or_equal_to: -1, less_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :mountains,
    foreign_key: 'creator_id'

  has_many :reviews
  has_many :upvotes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true, length: { in: 6..20 }

  def admin?
    role == "admin"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_users_path
  end

  def require_admin
    if !user_signed_in?
      redirect_to root_path
    elsif user_signed_in? == true && current_user.admin == false
      redirect_to root_path
    end
  end
end

app/controllers/api/v1/mountains_controller.rb
class Api::V1::MountainsController < ApplicationController
  skip_before_action :verify_authenticity_token
  protect_from_forgery unless: -> { request.format.json? }

  def index
    render json: Mountain.by_rating
  end

  def show
    mountain = Mountain.find(params[:id])
    render :json => {"mountain" => mountain, "reviews" => mountain.reviews}
  end

  def create
      mountain = JSON.parse(request.body.read)
      new_mountain = Mountain.create(
        name: mountain["name"],
        address: mountain["address"],
        city: mountain["city"],
        state: mountain["state"],
        zip: mountain["zip"],
        trail_count: mountain["trailCount"],
        ticket_price: mountain["ticketPrice"],
        rental_price: mountain["rentalPrice"],
        image_url: mountain["image_url"],
        creator_id: mountain["creator_id"]
      )
      render json: new_mountain
  end

  def show
    mountain = Mountain.find(params[:id])
    # render :json => {"mountain" => mountain, "reviews" => mountain.reviews, serializer: ReviewSerializer}
    render json: mountain
  end

  def destroy
    mountain = Mountain.find(params[:id])
    mountain.destroy
    render json: Mountain.by_rating
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController

  def create
    review = JSON.parse(request.body.read)
    @new_review = Review.new(
      rating: review["rating"],
      skiing_review: review["skiing_review"],
      food_review: review["food_review"],
      lodging_review: review["lodging_review"],
      user_id: review["user_id"],
      mountain_id: review["mountain_id"]
    )

    if @new_review.save
      UserReviewedItemMailer.email_mountain_creator(@new_review).deliver_now
      render json: @new_review
    else
      render json: {error: "Sorry, the review did not save and the email was not sent!"}
    end
  end

  def destroy
    review = Review.find(params[:id])
    mountain = review.mountain
    review.destroy
    render json: mountain.reviews
  end

end

app/controllers/api/v1/upvotes_controller.rb
class Api::V1::UpvotesController < ApplicationController
  skip_before_action :verify_authenticity_token
  protect_from_forgery unless: -> { request.format.json? }

  def create
    input = JSON.parse(request.body.read)
    user = User.find(input["userId"])
    review = Review.find(input["reviewId"])
    vote_value = input["vote"].to_i
    vote = user.upvotes.find_by(review: review)
    review.vote_total
    if vote
      if vote.vote == vote_value
        new_vote = 0
      else
        new_vote = vote_value
      end
      vote.update(vote: new_vote)
    else 
      new_vote = Upvote.create(
        user: user,
        review: review,
        vote: vote_value
      )
    end
    render json: review.mountain.reviews
  end
end

app/controllers/api/v1/user_controller.rb
class Api::V1::UserController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def is_signed_in?
    if user_signed_in?
      render :json => {"signed_in" => true, "user" => current_user}
    else
      render :json => {"signed_in" => false}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> {request.format.json?}
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :profile_pic_url])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username, :profile_pic_url])
 end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController

  def index
    # @mountains = Mountain.where("name ILIKE ?", params[:search])
    @search = params[:search]
    @mountains = Mountain.search(@search)
    # if !@mountains
    #   # redirect_to root_path
    # end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/views/admin/index.html.erb
<% @users.each do |user| %>
  <%= user.username %>
  <%= user.email %>
  <% if current_user.admin? %>
    <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
<% end %>

app/views/admin/users/index.html.erb
<h2>Registered Users</h2>

  <% @users.each do |user| %>
  <div class="user-list">
    <p>Username: <%= user.username %></p>
    <p>Email: <%= user.email %></p>
    <p>Role: <%= user.role %></p>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkiMountainReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag    'application' %>
  </head>

  <body>
    <nav class="container">
      <div class="search-div">
      <%= form_tag mountains_path, :method => 'get', :class => 'search-bar'  do %>
        <div>
          <%= text_field_tag :search, params[:search], :placeholder => "Search" %>
        </div>
      </div>
      <% end %>

      <div class="home">
        <%= link_to "Top Mountains", root_path %>
      </div>
      <div class="flasherror">
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      </div>
      <div class="sign-in">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>  /
        <%= link_to "View Profile", user_path(current_user.id) %>
        <% if current_user.admin? %>
           / <%= link_to "Admin View All Users", admin_users_path %>
        <% end %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> /
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
    </nav>
    <%= yield %>
    <div id="app"/>
  </body>
</html>

app/views/mountains/index.html.erb
<h2>Mountains Matching "<%= @search %>"</h2>
<div class="search-results">
<% @mountains.each do |mountain| %>
  <h4><%= link_to "#{mountain.name} - #{mountain.city}, #{mountain.state}", mountain_path(mountain.id) %></h4>
<% end %>
</div>

app/views/static_pages/index.html.erb
<p hidden> This is the main site</p>
<div id="app"></div>

app/views/users/show.html.erb
<h2><%= @user.username %> Profile Page</h2>

<div class="user-list">
<p>Username: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>
<p>Role: <%= @user.role %></p>
<%= link_to "Edit Profile", edit_user_registration_path %>
</div>